#!/bin/bash									
sudo su -								
sudo yum update -y									
sudo yum install httpd -y								
sudo service httpd start							
chkconfig httpd on							
sudo echo "WELCOME TO SERVER NO. $(hostname -i)" > /var/www/html/index.html 		
